spring:
  #profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/PerformanceAppraisal
    username: root
    password: qazwsx123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test